baseURL: https://example.com/
languageCode: zh-cn
title: Hugo-Theme-Xlog
copyright: Â© 2020-2024 Xlog

services:
  googleAnalytics:
    ID: G-xxxxx

# paginate specifies the maximum number of posts displayed on the home page.
pagination:
  pagerSize: 5
# theme specifies the name of the theme to be used.
theme: xlog
# defaultContentLanguage specifies the default language to use.
defaultContentLanguage: zh-cn
# language.xxx setup
languages:
  zh-cn:
    languageName: cn # will be displayed in the navbar.
    weight: 1
    params:
      greet: :) ä½ å¥½
      status: å­¦ç‰²ï¼Œ ç‰›é©¬ï¼Œ GDUTer . 
      description: |
        è¿™é‡Œæ˜¯ [L1nSn0w](https://linsnow.cn) çš„ Log. [æˆ‘](/pages/about)åœ¨è¿™é‡Œè®°å½•äº†ä¸€äº›æŠ€æœ¯ã€ç”Ÿæ´»ã€å­¦ä¹ ã€å¨±ä¹çš„å†…å®¹.
        è¿™é‡Œæœ‰æˆ‘çš„ä¸€äº›[æœ‹å‹](/pages/links),è¿˜æœ‰æˆ‘æ•æ‰åˆ°çš„ä¸€äº›[ç¬é—´](/pages/gallery),
        å¸Œæœ›ä½ èƒ½åœ¨è¿™é‡Œæ‰¾åˆ°ä½ æƒ³è¦çš„ä¸œè¥¿ã€‚ä¹Ÿå¸Œæœ›ä½ èƒ½åœ¨è¿™é‡Œç•™ä¸‹ä½ çš„è¶³è¿¹.  
  
  en:
    languageName: en
    weight: 2
    params:
      status: Student, GDUTer, Crazy. ğŸˆ
      description: |
        This is `L1nSn0w`'s `Log`. [Me](/pages/about) here records some technology, life, study, and entertainment content.ğŸ¤”
        I hope you can find what you want here. ğŸ‘£
      greet: :) Hello

params:
  # greet specifies greeting words.
  # greet: Hello :)
  # subtitle speficies a subtitle displayed right after the site title.
  subtitle:
  # minima has one dark theme and multiple light themes. defaultTheme specifies
  # a default light theme to use. currently available options: light, sand, rock, system.
  defaultTheme: light
  # displayDate speficies whether or not to display post date on the home page.
  displayDate: true
  # displayDescription specifies whether or not to display post description on
  # the home page.
  displayDescription: true
  # selectable specifies if or not your post content can be selected.
  selectable: true

  author: "author" # author
  description: "xxxxxxabcd" # site description
  keywords: ["Blog", "Log", "Hugo", "Theme"]  # site keywords

  icp: 
    enable: true
    icpurl: https://beian.miit.gov.cn/
    icpinfo: ç²¤ICPå¤‡xxxxxxxx

  # social is an array containing as many as social accounts to be displayed  
  # in the buttom of every page.
  social:
    - name: "email"
      url: "mailto:abcd@xx.com"
    - name: "github"
      url: "https://github.com/lin-snow"
    - name: "rss"
      url: "/index.xml"

  # image in grey style
  filterimg:
    enable: true

  # view-image plugin
  viewimage:
    enable: true

  # math plugin
  math:
    enable: true
    provider: katex

  # diagram plugin
  diagram:
    enable: true
    provider: mermaid

  # comment plugin
  comment:
    enable: true
    provider: twikoo
    # check out https://twikoo.js.org/
    twikoo:
      envId: https://comment.example.com
      region: ap-guangzhou # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œè…¾è®¯äº‘ç¯å¢ƒå¡« ap-shanghai æˆ– ap-guangzhouï¼›Vercel ç¯å¢ƒä¸å¡«
      lang: zh-CN # ç”¨äºæ‰‹åŠ¨è®¾å®šè¯„è®ºåŒºè¯­è¨€ï¼Œæ”¯æŒçš„è¯­è¨€åˆ—è¡¨ https://github.com/twikoojs/twikoo/blob/main/src/client/utils/i18n/index.js
    # check out https://artalk.js.org/
    artalk:
      server: https://artalk.example.com
      site: L1nSn0w's Log
    # check out https://waline.js.org/
    waline:
      serverURL: 
      placeholder: è¯´ç‚¹ä»€ä¹ˆå§...
      # check out https://valine.js.org
    # check out https://disqus.com/
    disqus:
      shortname: hugo-minima
      # check out https://utteranc.es
    utterances:
      repo: mivinci/hugo-theme-minima
      issueTerm: pathname
      label: comment
    # check out https://giscus.app
    giscus: 
      repo: mivinci/hugo-theme-minima
      repoId: MDEwOlJlcG9zaXRvcnkzODcxMjM2NDU=
      category: Comments
      categoryId: DIC_kwDOFxMJvc4CScQm
      mapping: pathname
      inputPosition: buttom # bottom | top
      reactions: true
      metadata: false
    

  # search plugin
  search:
    enable: true
    provider: fuse
    title: Search
    placeholder: Enter keywords
    # check out https://fusejs.io
    fuse:
      keys:
        - title
        - permalink
        - summary
        - content
      distance: 100
      location: 0
      threshold: 0.6
      ignoreLocation: false
      isCaseSensitive: false
      includeScore: false
      includeMatches: ture
      minMatchCharLength: 1
      shouldSort: true
      findAllMatches: true

  # éœé¹œæ–‡æ¥·å­—ä½“
  font_cleanwhite:
    enable: true
    cdn: https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css # <!-- Screen version -->


# menu.main is an array containing what is used as the navigator.
menu:
  main:
    - identifier: /
      name: home
      weight: 1
    - identifier: tags
      name: tags
      weight: 2
    - identifier: series
      name: series
      weight: 3
    - identifier: search
      name: search
      weight: 4


# taxonomies defines ways to classify yout posts. Below are some presets that
# most bloggers use, so you can replace them with whatever you like.
taxonomies:
  category: categories
  tag: tags
  series: series

# outputs tells Hugo the kind of files to be rendered.
outputs:
  home:
    - HTML
    - RSS
    - JSON

# markup.highlight has two keys set to make sure that the syntax highlighting
# in your posts are rendered correctly, so DO NOT edit them.
markup:
  highlight:
    lineNos: false
    noClasses: false
  goldmark:
    renderHooks:
      image:
        enableDefault: true
      parser:
        wrapStandAloneImageWithinParagraph: false
